url: http://presente.github.io/mothersday/
baseurl: http://presente.github.io/mothersday/

# Site settings
title: Mother's Day
email: info@presente.org
description: "No mother should be in detention"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
